import Link from 'next/link';
import { getScholarships } from '../university-queries';

export const dynamic = 'force-dynamic';

const regional = [
  { name:'Beijing Government Scholarship', level:'Municipal · Beijing', established:'Current municipal program', coverage:'Category A: tuition + accommodation + living expenses + medical insurance. Category B: tuition + accommodation + medical insurance. Category C: tuition + medical insurance.', eligibility:'International students in degree and selected non-degree programs; exact criteria and deadlines are set through participating institutions.', source:'https://english.beijing.gov.cn/studyinginbeijing/news/202601/t20260123_4459326.html' },
  { name:'Shanghai Municipal Government Scholarship', level:'Municipal · Shanghai', established:'Established in 2006', coverage:'Category A: tuition + accommodation + living expenses + medical insurance. Category B: tuition + medical insurance.', eligibility:'International students applying to participating Shanghai universities. Applications are generally handled around February–April, with university-specific deadlines.', source:'https://english.shanghai.gov.cn/en-ApplyforScholarships/20240208/a21ea5f94b2f42959635d72308606778.html' },
  { name:'Zhejiang Provincial Government Scholarship', level:'Provincial · Zhejiang', established:'Established in 2009', coverage:'Common published standards include Type A: RMB 30,000/year for postgraduate study and Type B: RMB 20,000/year for undergraduate study; exact category, quota and rules vary by annual notice/university.', eligibility:'International students applying to or studying at participating Zhejiang HEIs. English-taught applicants may need IELTS/TOEFL or equivalent; university rules apply.', source:'https://sie.zjgsu.edu.cn/gjen/ZhejiangProvincialGovernmentScholarship/list.htm' },
  { name:'Chinese Government Scholarship (CGS)', level:'National · China', established:'National government program', coverage:'Coverage depends on program/category; designated programs can include tuition, accommodation, living allowance and medical insurance.', eligibility:'International students across undergraduate, master, PhD and other supported categories; application route depends on the scholarship program.', source:'https://english.shanghai.gov.cn/en-FAQs-StudyinShanghai/20241015/239b38683117430d9e5a1376214699bc.html' },
];

export default async function Page(){
  const scholarships = await getScholarships();
  return <main><Header/><section className="page-head reveal"><div className="eyebrow">FUNDING DIRECTORY</div><h1>Scholarships</h1><p>University-linked awards plus major national and regional funding routes. Coverage is shown only where the source supports it.</p></section><section className="section">
    <div className="section-head"><div><div className="eyebrow">REGIONAL + NATIONAL</div><h2>Government scholarships</h2></div></div>
    <div className="scholar-grid regional-grid">{regional.map(s=><article className="scholar-card regional-card" key={s.name}><div className="tag">{s.level}</div><h3>{s.name}</h3><p><b>Established:</b> {s.established}</p><p>{s.coverage}</p><p><b>Eligibility:</b> {s.eligibility}</p><a className="btn secondary" href={s.source} target="_blank" rel="noreferrer">Official details ↗</a></article>)}</div>
  </section><section className="section muted"><div className="section-head"><div><div className="eyebrow">DATABASE</div><h2>University-linked scholarships</h2></div></div><div className="scholar-grid">{scholarships.map(s=><article className="scholar-card" key={s.id}><div className="tag">{s.scholarship_type || 'Scholarship'} · {s.provider || 'Provider varies'}</div><h3>{s.name}</h3><p>{s.description || 'Verify the current scholarship call for eligibility, benefits and deadline.'}</p><div className="chips">{s.tuition_coverage && <span>Tuition</span>}{s.accommodation_coverage && <span>Accommodation</span>}{s.stipend_coverage && <span>Stipend</span>}{s.insurance_coverage && <span>Insurance</span>}</div><p><b>{s.university_count}</b> linked universities{s.application_deadline ? ` · Deadline ${s.application_deadline}` : ''}</p>{(s.application_url || s.official_website) && <a href={s.application_url || s.official_website} target="_blank" rel="noreferrer">Application / official details ↗</a>}</article>)}</div>{!scholarships.length && <div className="panel empty"><h2>No university-linked scholarships yet.</h2><p>Government scholarship information is shown above while university-specific records are collected.</p></div>}</section></main>
}
function Header(){return <header className="nav"><Link className="brand" href="/">China<span>Uni</span>Tracker</Link><nav><Link href="/universities">Universities</Link><Link href="/scholarships">Scholarships</Link><Link href="/csca">CSCA</Link><Link href="/contact">Contact</Link></nav></header>}
