import {NextResponse} from "next/server";
import {sql} from "@neondatabase/serverless";
import {cookies} from "next/headers";
import {readSession} from "../../../../../lib/admin-auth";
function admin(){return readSession(cookies().get("cut_admin_session")?.value)}
const U=new Set(["name_english","name_chinese","short_name","university_type","city","province","official_website","university_description","admissions_website","logo_url","cover_image_url","c9","project_985","project_211","double_first_class"]);
const P=new Set(["program_name","degree_level","language","english_taught","field_of_study","duration_years","tuition_fee","tuition_currency","official_program_url","application_url","is_active"]);
export async function GET(req){if(!admin())return NextResponse.json({error:"Unauthorized"},{status:401});try{const db=sql(process.env.DATABASE_URL);const q=new URL(req.url).searchParams.get("q")||"";const rows=await db`SELECT u.id,u.name_english,u.city,u.province,u.official_website,COUNT(p.id)::int program_count FROM universities u LEFT JOIN programs p ON p.university_id=u.id WHERE u.country='China' AND (u.name_english ILIKE ${'%'+q+'%'} OR COALESCE(u.name_chinese,'') ILIKE ${'%'+q+'%'}) GROUP BY u.id ORDER BY u.name_english LIMIT 100`;return NextResponse.json({universities:rows})}catch{return NextResponse.json({error:"Unable to load universities"},{status:500})}}
export async function PATCH(req){const a=admin();if(!a)return NextResponse.json({error:"Unauthorized"},{status:401});try{const b=await req.json();const db=sql(process.env.DATABASE_URL);if(!b.id||!b.type||!b.field)return NextResponse.json({error:"id, type and field are required"},{status:400});const allowed=b.type==='university'?U:P;if(!allowed.has(b.field))return NextResponse.json({error:"Field is not editable"},{status:400});const table=b.type==='university'?'universities':'programs';const id=String(b.id);const field=b.field;const value=b.value===undefined?null:b.value;const query=`UPDATE ${table} SET ${field}=$1, updated_at=now() WHERE id=$2 RETURNING id`;const result=await db.query(query,[value,id]);if(!result[0])return NextResponse.json({error:"Record not found"},{status:404});await db`INSERT INTO admin_audit_logs (admin_email,action,entity_type,entity_id,details) VALUES (${a.email},'field_update',${b.type},${id},${JSON.stringify({field,value})})`;return NextResponse.json({ok:true,id:result[0].id})}catch{return NextResponse.json({error:"Unable to update record"},{status:500})}}
