import Link from 'next/link';
import { getProgramById } from '../../../../university-queries';

export const dynamic = 'force-dynamic';

export default async function ProgramPage({ params }) {
  const p = await getProgramById(params.programId);
  if (!p || String(p.university_id) !== String(params.slug)) return <main><Header/><section className="page-head"><h1>Program not found.</h1><Link className="btn secondary" href="/universities">Back to directory</Link></section></main>;
  const rankUrl = `https://www.shanghairanking.com/universities/${p.university_name.toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`;
  const latestIntake = p.intakes?.[0];
  const requirements = [
    ['English requirement', p.english_requirement || (p.ielts_min ? `IELTS ${p.ielts_min}` : null)],
    ['TOEFL', p.toefl_min ? `Minimum ${p.toefl_min}` : null],
    ['HSK', p.hsk_requirement],
    ['Academic minimum', p.minimum_percentage ? `${p.minimum_percentage}%` : null],
    ['Mathematics', p.mathematics_required == null ? null : (p.mathematics_required ? 'Required' : 'Not required')],
    ['CSCA', p.csca_required ? `Required${p.csca_subjects ? ` · ${p.csca_subjects}` : ''}` : 'Not listed as required'],
  ].filter(([,v]) => v);
  return <main><Header/><section className="program-hero reveal"><div><Link className="back-link" href={`/universities/${p.university_id}`}>← {p.university_name}</Link><div className="eyebrow">PROGRAM DETAILS</div><h1>{p.program_name}</h1><div className="program-meta"><span>{p.degree_level}</span><span>{p.language || 'Language to verify'}</span><span>{p.duration_years ? `${p.duration_years} years` : 'Duration to verify'}</span></div></div><div className="program-hero-actions"><a className="btn primary" href={p.official_program_url || p.admissions_website || p.official_website} target="_blank" rel="noreferrer">Apply / official page ↗</a><a className="btn secondary" href={rankUrl} target="_blank" rel="noreferrer">ShanghaiRanking ↗</a></div></section>
  <section className="detail-grid program-grid"><div>
    <article className="panel pricing-panel"><h2>Cost & funding</h2><div className="cost-table"><div><span>Published tuition</span><b>{p.tuition_fee ? `${p.tuition_fee} ${p.tuition_currency || 'RMB'}` : 'Not verified'}</b></div><div><span>After scholarship</span><b>Depends on award</b></div><div><span>Accommodation</span><b>Check university / scholarship</b></div><div><span>Application fee</span><b>Not verified</b></div></div><p className="muted-note">We never invent a discounted tuition figure. When a scholarship explicitly waives tuition, the award is shown below and the net cost can be calculated once the published tuition and award are both verified.</p></article>
    <article className="panel"><h2>Requirements</h2>{requirements.length ? <div className="requirements-list">{requirements.map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div> : <p>No structured requirements have been verified yet. Use the official program page before applying.</p>}</article>
    <article className="panel"><h2>Scholarships available</h2>{p.scholarships.length ? <div className="scholar-grid">{p.scholarships.map(s=><div className="scholar-card" key={s.id}><div className="tag">{s.scholarship_type || 'Scholarship'} · {s.provider || 'Provider varies'}</div><h3>{s.name}</h3><p>{s.description || 'Current award details need verification.'}</p><div className="chips small">{s.tuition_coverage && <span>Tuition</span>}{s.accommodation_coverage && <span>Accommodation</span>}{s.stipend_coverage && <span>Stipend</span>}{s.insurance_coverage && <span>Insurance</span>}</div>{s.application_deadline && <small>Deadline: {s.application_deadline}</small>}{(s.application_url || s.official_website) && <p><a href={s.application_url || s.official_website} target="_blank" rel="noreferrer">Scholarship details ↗</a></p>}</div>)}</div> : <p>No university-linked scholarship has been verified for this program yet.</p>}</article>
    <article className="panel"><h2>Application timeline</h2>{latestIntake ? <div className="requirements-list"><div><span>Intake</span><b>{latestIntake.name || 'September'}</b></div><div><span>Application opens</span><b>{latestIntake.open ? new Date(latestIntake.open).toLocaleDateString('en-IN') : 'Not verified'}</b></div><div><span>Deadline</span><b>{latestIntake.deadline ? new Date(latestIntake.deadline).toLocaleDateString('en-IN') : 'Not verified'}</b></div><div><span>Status</span><b>{latestIntake.status || 'Check official notice'}</b></div></div> : <p>No structured intake deadline is available yet.</p>}</article>
    <article className="panel"><h2>Official sources</h2>{p.sources.length ? <ul className="source-list">{p.sources.map(s=><li key={s.id}><a href={s.source_url} target="_blank" rel="noreferrer">{s.source_name || 'Official source'} ↗</a><small>{s.verification_status || 'Unverified'}{s.last_checked_at ? ` · checked ${new Date(s.last_checked_at).toLocaleDateString('en-IN')}` : ''}</small></li>)}</ul> : <p>No source record is attached yet.</p>}</article>
  </div><aside><div className="panel"><div className="tag">UNIVERSITY</div><h3>{p.university_name}</h3><p>{p.city || 'China'}{p.province ? `, ${p.province}` : ''}</p><div className="chips">{p.c9 && <span>C9</span>}{p.project_985 && <span>985</span>}{p.project_211 && <span>211</span>}{p.double_first_class && <span>Double First-Class</span>}</div></div><div className="panel"><h3>Contacts</h3>{p.contacts.length ? p.contacts.map(c=><div key={c.id} className="contact-row"><b>{c.department || c.contact_type || 'Admissions'}</b><p>{c.email || '—'}<br/>{c.phone || ''}</p></div>) : <p>Official contact details are not verified yet.</p>}</div><div className="panel"><h3>Useful links</h3>{p.official_website && <a className="btn secondary full" href={p.official_website} target="_blank" rel="noreferrer">University website ↗</a>}{p.admissions_website && <a className="btn secondary full" href={p.admissions_website} target="_blank" rel="noreferrer">Admissions portal ↗</a>}<a className="btn secondary full" href={rankUrl} target="_blank" rel="noreferrer">ShanghaiRanking profile ↗</a></div></aside></section></main>
}
function Header(){return <header className="nav"><Link className="brand" href="/">China<span>Uni</span>Tracker</Link><nav><Link href="/universities">Universities</Link><Link href="/scholarships">Scholarships</Link><Link href="/csca">CSCA</Link><Link href="/contact">Contact</Link></nav></header>}
