import Link from 'next/link';
import { getUniversities, getScholarships } from './university-queries';

export const dynamic = 'force-dynamic';

export default async function Home(){
  const [universities, scholarships] = await Promise.all([getUniversities({}), getScholarships()]);
  return <main><Header/><section className="hero reveal"><div><div className="eyebrow">CHINA STUDY DISCOVERY PLATFORM</div><h1>Find the right university in China without the chaos.</h1><p>Compare English-taught Bachelor&apos;s and Master&apos;s programs, scholarships, fees, admissions requirements and CSCA information in one place.</p><div className="actions"><Link className="btn primary" href="/universities">Explore universities</Link><Link className="btn secondary" href="/scholarships">Explore scholarships</Link></div></div><div className="hero-card"><b>2027 INTAKE · LIVE DATABASE</b><h3>Study in China</h3><p>Programs · Scholarships · Requirements · Deadlines</p><div className="mini-grid"><div><strong>{universities.length}</strong><span>universities in database</span></div><div><strong>{scholarships.length}</strong><span>scholarship records</span></div></div></div></section><section className="stats reveal"><div><b>Programs</b><span>English-taught discovery</span></div><div><b>Degrees</b><span>Bachelor + Master</span></div><div><b>Funding</b><span>Scholarships</span></div><div><b>Guidance</b><span>Admissions + CSCA</span></div></section><section className="section reveal"><div className="section-head"><div><div className="eyebrow">DISCOVER</div><h2>Start with what matters</h2></div></div><div className="feature-grid"><Link href="/universities" className="feature"><span>01</span><h3>Universities</h3><p>Public/private status, location, programs, tuition, facilities and admissions.</p></Link><Link href="/scholarships" className="feature"><span>02</span><h3>Scholarships</h3><p>CSC and university funding opportunities with eligibility and application routes.</p></Link><Link href="/csca" className="feature"><span>03</span><h3>CSCA Hub</h3><p>Exam dates, registration windows, subjects and preparation resources.</p></Link></div></section><section className="section muted reveal"><div className="section-head"><div><div className="eyebrow">LIVE DATA</div><h2>Universities to explore</h2></div><Link href="/universities">Full directory →</Link></div><div className="uni-grid">{universities.slice(0,6).map(u=><Link className="uni-card" href={`/universities/${u.id}`} key={u.id}><div className="uni-logo">{u.short_name || u.name_english.slice(0,3).toUpperCase()}</div><div><div className="tag">{u.university_type} · {classification(u)}</div><h3>{u.name_english}</h3><p>{u.city}, {u.province || 'China'}</p></div></Link>)}</div></section></main>
}
function classification(u){ if(u.c9) return 'C9'; if(u.double_first_class) return 'Double First-Class'; if(u.project_985) return '985'; if(u.project_211) return '211'; return 'University'; }
function Header(){return <header className="nav"><Link className="brand" href="/">China<span>Uni</span>Tracker</Link><nav><Link href="/universities">Universities</Link><Link href="/scholarships">Scholarships</Link><Link href="/csca">CSCA</Link><Link href="/contact">Contact</Link></nav></header>}
