import Link from 'next/link';
import { getUniversityById } from '../../university-queries';
import ReportButton from '../../components/report-button';

export const dynamic = 'force-dynamic';

export default async function Page({ params }) {
  const u = await getUniversityById(params.slug);
  if (!u) return <main><Header/><section className="page-head"><h1>University not found.</h1><Link className="btn secondary" href="/universities">Back to directory</Link></section></main>;
  const verifiedDates = u.sources.map((s) => s.last_checked_at).filter(Boolean).sort();
  const lastVerified = verifiedDates.length ? new Date(verifiedDates[verifiedDates.length - 1]).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }) : null;
  return <main><Header/><section className="detail-hero"><div className="uni-logo big">{u.short_name || u.name_english.slice(0,3).toUpperCase()}</div><div><div className="tag">{u.university_type} · {classification(u)}</div><h1>{u.name_english}</h1><p>{u.city || 'China'}{u.province ? `, ${u.province}` : ''}</p>{lastVerified && <div className="verified-badge">✓ Source record checked · {lastVerified}</div>}</div></section><section className="detail-grid"><div>
    <article className="panel"><h2>About</h2><p>{u.university_description || 'University profile information is being verified and expanded.'}</p><div className="chips">{u.c9 && <span>C9</span>}{u.project_985 && <span>985</span>}{u.project_211 && <span>211</span>}{u.double_first_class && <span>Double First-Class</span>}</div><ReportButton university={u.name_english}/></article>
    <article className="panel"><h2>Programs</h2>{u.programs.length ? <div className="table-wrap"><table><thead><tr><th>Program</th><th>Degree</th><th>Language</th><th>Duration</th><th>Tuition</th><th>CSCA</th><th>Subjects</th><th>Deadline</th></tr></thead><tbody>{u.programs.map(p=><tr key={p.id}><td><b>{p.program_name}</b><br/><small>{p.field_of_study || ''}</small><br/><ReportButton university={u.name_english} program={p.program_name}/></td><td>{p.degree_level}</td><td>{p.language || (p.english_taught ? 'English' : '—')}</td><td>{p.duration_years ? `${p.duration_years} years` : '—'}</td><td>{p.tuition_fee ? `${p.tuition_fee} ${p.tuition_currency || ''}` : 'To verify'}</td><td>{p.csca_required ? 'Required' : 'Not listed'}</td><td>{p.csca_subjects || '—'}</td><td>{p.intakes?.[0]?.deadline ? new Date(p.intakes[0].deadline).toLocaleDateString('en-IN') : '—'}</td></tr>)}</tbody></table></div> : <p>No programs have been entered yet.</p>}</article>
    <article className="panel"><h2>Scholarships</h2>{u.scholarships.length ? <div className="scholar-grid">{u.scholarships.map(s=><div className="scholar-card" key={s.id}><h3>{s.name}</h3><p>{s.description || 'University-linked scholarship. Verify the current call.'}</p><div className="chips small">{s.tuition_coverage && <span>Tuition</span>}{s.accommodation_coverage && <span>Accommodation</span>}{s.stipend_coverage && <span>Stipend</span>}</div></div>)}</div> : <p>No scholarship links have been entered yet.</p>}</article>
    <article className="panel"><h2>Campus & facilities</h2>{u.campuses.map(c=><div key={c.id}><h3>{c.name}</h3><p>{c.city || u.city}{c.address ? ` · ${c.address}` : ''}</p><p>{c.description || ''}</p></div>)}{u.campuses.length===0 && <p>Campus information is being collected.</p>}</article>
    <article className="panel"><h2>Verification sources</h2>{u.sources.length ? <ul>{u.sources.map(s=><li key={s.id}><a href={s.source_url} target="_blank" rel="noreferrer">{s.source_name} ↗</a> — {s.verification_status || 'Unverified'}{s.last_checked_at ? ` · checked ${new Date(s.last_checked_at).toLocaleDateString('en-IN')}` : ''}</li>)}</ul> : <p>No source records yet. Critical admissions facts should be verified on the official website.</p>}</article>
  </div><aside><div className="panel"><h3>Official links</h3>{u.official_website && <a className="btn primary full" href={u.official_website} target="_blank" rel="noreferrer">Official website ↗</a>}{u.admissions_website && <a className="btn secondary full" href={u.admissions_website} target="_blank" rel="noreferrer">Admissions ↗</a>}</div><div className="panel"><h3>Contacts</h3>{u.contacts.length ? u.contacts.map(c=><div key={c.id}><b>{c.department || c.contact_type || 'Contact'}</b><p>{c.email || '—'}<br/>{c.phone || ''}</p></div>) : <p>Official contact details are not entered yet.</p>}</div><div className="panel warning"><b>Verification</b><p>CUCAS is an aggregator source. Critical fees, deadlines, contacts and eligibility should be confirmed against the university's official notice before applying.</p></div></aside></section></main>
}
function classification(u){ if(u.c9) return 'C9'; if(u.double_first_class) return 'Double First-Class'; if(u.project_985) return '985'; if(u.project_211) return '211'; return 'University'; }
function Header(){return <header className="nav"><Link className="brand" href="/">China<span>Uni</span>Tracker</Link></header>}
