"use client";
import {useEffect,useState} from "react";
import "../admin.css";

export default function AdminReviews(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/reviews",{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.error);setItems(j.reviews||[])}catch(e){setError(e.message||"Unable to load reviews")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function update(id,patch){const r=await fetch("/api/admin/reviews",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,...patch})});if(!r.ok){const j=await r.json();setError(j.error||"Update failed");return}load()}
 return <main className="admin-dashboard"><header className="admin-head"><div><div className="admin-kicker">REVIEW QUEUE</div><h1>Needs Admin Review</h1><p>Inspect, annotate and verify records before publishing.</p></div><a href="/admin/dashboard">← Dashboard</a></header>{error&&<div className="admin-error">{error}</div>}{loading?<section className="admin-panel">Loading review queue…</section>:items.length===0?<section className="admin-panel"><h2>Nothing waiting</h2><p className="muted">No records are currently marked for admin review.</p></section>:<section className="review-list">{items.map(x=><article className="review-card" key={x.id}><div className="review-card-head"><div><span className="admin-kicker">{x.priority} priority</span><h2>{x.university_name||"Unknown university"}</h2><p>{x.program_name||"University-level review"} {x.degree_level?`· ${x.degree_level}`:""} {x.language?`· ${x.language}`:""}</p></div><select value={x.status} onChange={e=>update(x.id,{status:e.target.value,priority:x.priority,reason:x.reason,admin_notes:x.admin_notes})}><option value="needs_review">Needs review</option><option value="in_progress">In progress</option><option value="verified">Verified</option><option value="published">Published</option></select></div><label>Reason<textarea defaultValue={x.reason||""} id={`reason-${x.id}`} /></label><label>Admin notes<textarea defaultValue={x.admin_notes||""} id={`notes-${x.id}`} /></label><div className="review-card-actions"><button onClick={()=>update(x.id,{status:"in_progress",priority:x.priority,reason:document.getElementById(`reason-${x.id}`)?.value,admin_notes:document.getElementById(`notes-${x.id}`)?.value})}>Save notes</button><button onClick={()=>update(x.id,{status:"verified",priority:x.priority,reason:document.getElementById(`reason-${x.id}`)?.value,admin_notes:document.getElementById(`notes-${x.id}`)?.value})}>Mark verified</button><button onClick={()=>update(x.id,{status:"published",priority:x.priority,reason:document.getElementById(`reason-${x.id}`)?.value,admin_notes:document.getElementById(`notes-${x.id}`)?.value})}>Publish</button>{x.official_program_url&&<a href={x.official_program_url} target="_blank" rel="noreferrer">Official source ↗</a>}</div></article>)}</section>}</main>
}
