"use client";
import {useEffect,useState} from "react";
import "../admin.css";

const universityFields=["name_english","name_chinese","short_name","university_type","city","province","official_website","admissions_website","university_description","logo_url","cover_image_url","c9","project_985","project_211","double_first_class"];
const programFields=["program_name","degree_level","language","english_taught","field_of_study","duration_years","tuition_fee","tuition_currency","official_program_url","application_url","is_active"];
function label(x){return x.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
function Field({type,id,name,value,onSaved}){const [v,setV]=useState(value??"");const [busy,setBusy]=useState(false);async function save(){setBusy(true);const r=await fetch("/api/admin/universities",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,id,field:name,value:v})});setBusy(false);if(r.ok)onSaved?.();}return <div className="editor-field"><label>{label(name)}</label><div className="editor-row">{typeof value==="boolean"?<select value={String(v)} onChange={e=>setV(e.target.value==="true")}><option value="true">Yes</option><option value="false">No</option></select>:name.includes("description")?<textarea value={v} onChange={e=>setV(e.target.value)}/>:<input value={v} onChange={e=>setV(e.target.value)}/>}<button onClick={save} disabled={busy}>{busy?"Saving…":"Save"}</button></div></div>}
export default function AdminUniversities(){const [q,setQ]=useState(""),[items,setItems]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState("");async function load(){const r=await fetch(`/api/admin/universities?q=${encodeURIComponent(q)}`,{cache:"no-store"});const j=await r.json();if(r.ok)setItems(j.universities||[]);else setError(j.error)}useEffect(()=>{load()},[]);async function open(id){const r=await fetch(`/api/admin/universities?id=${id}`,{cache:"no-store"});const j=await r.json();if(r.ok)setSelected(j);else setError(j.error)}return <main className="admin-dashboard"><header className="admin-head"><div><div className="admin-kicker">DATA EDITOR</div><h1>Universities</h1><p>Inspect and update live database records.</p></div><a href="/admin/dashboard">← Dashboard</a></header>{error&&<div className="admin-error">{error}</div>}<section className="admin-panel"><div className="editor-search"><input placeholder="Search university…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/><button onClick={load}>Search</button></div><div className="editor-list">{items.map(u=><button key={u.id} onClick={()=>open(u.id)}><b>{u.name_english}</b><span>{u.city||"China"}{u.province?`, ${u.province}`:""} · {u.program_count} programs</span></button>)}</div></section>{selected&&<section className="admin-panel"><div className="editor-title"><div><span className="admin-kicker">UNIVERSITY RECORD</span><h2>{selected.university.name_english}</h2></div><button onClick={()=>setSelected(null)}>Close</button></div><h3>University details</h3>{universityFields.map(f=><Field key={f} type="university" id={selected.university.id} name={f} value={selected.university[f]} onSaved={()=>open(selected.university.id)}/>)}<h3>Programs</h3>{selected.programs.length?selected.programs.map(p=><article className="editor-program" key={p.id}><h4>{p.program_name}</h4>{programFields.map(f=><Field key={f} type="program" id={p.id} name={f} value={p[f]} onSaved={()=>open(selected.university.id)}/>)}</article>):<p className="muted">No program records.</p>}</section>}</main>}
